export const articleTeamHeader: string;
export const left: string;
export const right: string;
export const article: string;
export const articlePostData: string;
export const articleBody: string;
export const articleImage: string;
export const articleText: string;
export const videoWrapper: string;
